// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseInput: typeof import('./src/components/BaseInput.vue')['default']
    BaseLoader: typeof import('./src/components/BaseLoader.vue')['default']
    BaseModal: typeof import('./src/components/BaseModal.vue')['default']
    BasePaging: typeof import('./src/components/BasePaging.vue')['default']
    BasePopover: typeof import('./src/components/BasePopover.vue')['default']
    BaseTable: typeof import('./src/components/BaseTable.vue')['default']
    BaseToast: typeof import('./src/components/BaseToast.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IMdiAccountMultiple: typeof import('~icons/mdi/account-multiple')['default']
    IMdiAlert: typeof import('~icons/mdi/alert')['default']
    IMdiAlertOctagonOutline: typeof import('~icons/mdi/alert-octagon-outline')['default']
    IMdiChevronLeft: typeof import('~icons/mdi/chevron-left')['default']
    IMdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    IMdiClose: typeof import('~icons/mdi/close')['default']
    IMdiContentSave: typeof import('~icons/mdi/content-save')['default']
    IMdiDotsHorizontal: typeof import('~icons/mdi/dots-horizontal')['default']
    IMdiFileDocumentMultipleOutline: typeof import('~icons/mdi/file-document-multiple-outline')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiHeadQuestionOutline: typeof import('~icons/mdi/head-question-outline')['default']
    IMdiHomeOutline: typeof import('~icons/mdi/home-outline')['default']
    IMdiInformationOutline: typeof import('~icons/mdi/information-outline')['default']
    IMdiLock: typeof import('~icons/mdi/lock')['default']
    IMdiLogin: typeof import('~icons/mdi/login')['default']
    IMdiMagnify: typeof import('~icons/mdi/magnify')['default']
    IMdiMenu: typeof import('~icons/mdi/menu')['default']
    IMdiRefresh: typeof import('~icons/mdi/refresh')['default']
    IMdiScaleBalance: typeof import('~icons/mdi/scale-balance')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdatePrompt: typeof import('./src/components/UpdatePrompt.vue')['default']
  }
}
